Terms & Conditions
The conditions will apply directly to you if you install or use the service provided via our app. It should be necessary for a user to know about the T&C before start using the app. 
    • The app, any element of the app, or our trademarks may not be copied or modified in any form. The permission to extract the app’s source code is not granted to the user. Furthermore, you should not translate it into other languages or create derivative versions. One Solution retains ownership of the app, as well as all trademarks, copyright, database rights, and other intellectual property rights associated with it.
    • One Solution is dedicated to making the app as effective and useful as possible. As a result, we reserve the right to make changes to the app at any time and for any reason, as well as to charge for its services. We did not charge anything from you for the app or the services provided unless we have made it transparent clear what you are paying for.
    • The “One Solution” app safely stores and processes personal data that you have submitted to us. It is solely your responsibility to keep your phone and app safe. As a result, we do not suggest jailbreaking or rooting your phone, which is the process of eliminating software restrictions and constraints imposed by your device’s official operating system. It may expose your phone to malware/viruses/malicious apps, weaken your phone’s security features, and cause the One Solution app to stop working properly or at all.
    • You ought to be informed that there are things for which One Solution will be not being held liable. Certain features of the app will demand that it be connected to the internet. The connection can be Wi-Fi or provided by your mobile network carrier, but One Solution cannot be held liable if the app does not function properly because you do not have access to Wi-Fi and your data quota has run out.
    • If you’re using the app outside of a Wi-Fi hotspot, keep in mind that the conditions of your mobile network provider’s agreement will still apply. As a result, your cell provider may charge you for data usage for the duration of the connection while using the app, as well as additional third-party fees. In case, you use the app outside your region or nation i.e. of home territory without turning off data roaming, you accept responsibility for any such charges. Please be aware that if you are not the billing provider for the phone on which you are using the app, we will assume that the bill payer has given you the permission to use the app.
    • In a similar vein, One Solution cannot always be held liable for how you use the app, i.e. you must keep your device charged; if it runs out of energy and you are unable to turn it on to use the Service, One Solution will not be liable.
    • When it comes to One Solution’s obligation for your use of app, it’s important to remember that, while we strive to keep it up to date and accurate throughout all times, we sometimes depend on third parties to give details to us because we may make it available to you. One Solution takes no responsibility for any direct or indirect loss you may incur as a result of depending solely on this app’s functionality.
    • We may want to upgrade the app at some point. The app is now available on Android and iOS; however, the requirements for these systems (and any more systems to which we decide to expand the app’s availability) may change, and you’ll need to download updates to keep using the app. One Solution does not guarantee that the app will always be relevant to you and/or compatible with the Android and iOS versions you have installed on your device. However, be ready to accept application updates when they are offered to you. We may also decide to stop providing the app and may terminate your use of it at any time without notice to you. If we terminate these terms, (a) the permissions and licenses accorded to you in the terms will terminate; (b) you shall stop using the app and (if necessary) erase it from the device.
Terms and Conditions Modifications
From time to time, we modify our Terms and Conditions. So, you should check this page for more updates on a regular basis. Any modifications will be communicated to you by posting the revised Terms and Conditions on this page.
These terms and conditions are in place as of September 29the, 2021.
Get in Touch With Us
Please email us at contact if you have any queries or recommendations concerning our Terms & Conditions.
